### ISSUE TITLE
POST returns non-JSON payload

### ISSUE THREAD

**Issue by Szasza** [Mermade/openapi-webconverter#2]
Hi Mark,

Great job so far, thank you for maintaining the package.

I would like to flag an issue with the POST validate endpoint. If I send a yaml content with `application/json` accept header, the response I get back has the header `Content-Type: application/json` but the response payload is actually not a JSON but a `status: true` in plain text without curly braces.

Happy to investigate and create a PR as needed.

**Comment by MikeRalphson** [comment]
Thanks for reporting it, and for the offer of a PR! Let me know if you don't get a chance to work on it and I'll have a look. I think it's assuming yaml output for yaml input and not checking the `Accept` header.

**Comment by MikeRalphson** [comment]
Thanks again for the fix.

**Comment by Szasza** [comment]
My pleasure.
