### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by hlubovac** [Mermade/openapi-webconverter#4]
Hi - 

Your other tool (https://github.com/Mermade/openapi-gui) attempts to communicate with hosted "converter" (when provided swagger-json is v2); however, it won't work because of cross-domain configuration is missing on the target (https://openapi-converter.herokuapp.com/api/v1/convert). Just thought I should report this :)

Thanks.
Hari

**Comment by MikeRalphson** [comment]
Thanks, will take a look, I thought I had CORS all sorted...

**Comment by hlubovac** [comment]
The client was localhost, in case that's not clear.

**Comment by MikeRalphson** [comment]
As would have been all my testing... Odd.

**Comment by MikeRalphson** [comment]
I'm seeing the following headers from a GET to that URL:

Header|Value
|---|---|
Access-Control-Allow-Origin|*
Connection|keep-alive
Content-Length| 0
Date|Thu, 16 Nov 2017 19:27:28 GMT
Etag|W/"49-X72oYqVsVLYn91obKqqyDKlm+w4"
Server|Cowboy
Via|1.1 vegur
X-Powered-By|Express

All the writes to the `httpResponse` should go through `sendObj` which sets the Access-Control-Allow-Origin header.

Can you paste the headers you see (and let me know if it's a GET or POST request)?

**Comment by hlubovac** [comment]
I'm sorry, but I can't quickly do that (my integration is funky; long story; and I already reverted what I started).

I did try again with a different setup (as static site), and it loaded the sample w/o problems (but the sample probably gets v3 swagger, so the flow is different).

During my previous attempt, I remember having to change the two URLs within index.html file to https (maybe setting them without protocol: "//generator..." would work also) - so that I can see whether the rest of the app would work for me.

Then I was setting breakpoints until I reched `convertOpenApi2' (index.html, line 123 currently).

I didn't pay attention to this then, but this will answer your question (it's a POST):

```
function convertOpenApi2(schema,callback) {
    var convertUrl;
    if (window.intelligentBackend) convertUrl = '/api/v1/convert';
    else convertUrl = 'https://openapi-converter.herokuapp.com/api/v1/convert';
    var data = new FormData();
    data.append('source',JSON.stringify(schema));
    $.ajax({
        url:convertUrl,
        type:"POST",
        contentType: false,
        processData: false,
        data:data,
        dataType:"json",
        success: function(schema) {
            callback(schema);
        }
    });
}
```

Again, this is within "openapi-gui" project; file: `\openapi-gui-master\src\app\app.js`.

I now realized that this project, being an editor, isn't quite for me (at this time) - as I was searching for read-only swagger-ui implementations. But it looks great. I just can't find a purpose for it, because my system is the opposite: it generates swagger-json, then needing a UI to show details on it; while this one seems to be a tool for describing already existing endpoints. While I could still use it to display service information, it can't be editable (unless that part can be switched off).

**Comment by hlubovac** [comment]
I kept trying, though :) I want to help you. I'm not sure how much, though, cause I'm about to say something that contradicts what I reported earlier (unless you just changed settings on the server to make this work).

So, I provided the url to my swagger-json source via query on index.html (something I forgot; previously my code did this for me, so I didn't pay attention).

And, surprisingly, retrieving a converted version from your running converter-app worked! So, I provided v2, got v3.

However, the app choked on produced v3 with this JS error:

![image](https://user-images.githubusercontent.com/3127736/32915896-a774342e-cad7-11e7-94cf-e6aeba843298.png)

Latest Chrome :)

![image](https://user-images.githubusercontent.com/3127736/32916142-5e8ce958-cad8-11e7-9056-1a9f0ae0b1fd.png)

I can't give you the URL to point to for a sample swagger-json (because it's not public), but I can give you content that should reproduce this JS error: 
[swagger-json-v2.txt](https://github.com/Mermade/openapi-webconverter/files/1480256/swagger-json-v2.txt)

I hope that helps.

Hari

**Comment by MikeRalphson** [comment]
Thanks very much for the detailed write-up. I'll try and fix the JS error - the screen orientation locking never worked correctly anyway.

As to a read-only swagger-ui replacement, have you looked at [ReDoc](https://github.com/Rebilly/ReDoc) ?

**Comment by hlubovac** [comment]
I already have several integrated into my solution, ReDoc being one of them - so, yes, thank you. The documentation part of my service allows the user to switch between UI's that can work with swagger-json, for the reason of features, performance, etc. When I discovered yours, I wanted to see whether it will also work as an additional. So far, I have 8 of them :) Perhaps an overkill, but if it takes little effort to add more, why not.

**Comment by MikeRalphson** [comment]
I'd be interested to see that! There may be a couple more at https://github.com/Mermade/awesome-openapi3 worth checking out. I guess you've seen https://github.com/APIs-guru/openapi-directory which I also maintain.

**Comment by hlubovac** [comment]
It's not anything super-special.

Imagine an index page, with the list of available UI's (based on configuration, or existence of respective folders that each contain static HTML files for various swagger-ui's).

![image](https://user-images.githubusercontent.com/3127736/32919841-706b8772-cae4-11e7-8053-23380fa23915.png)

![image](https://user-images.githubusercontent.com/3127736/32919850-7b7d57f8-cae4-11e7-8453-b0c81573e7e4.png)

Then, they each link to a webpage that contains nothing but an iframe without src attribute (taking up all body-space). The containing page executes code on-load that grabs ui-id from the query, constructs the URL that iframe (which contains matching folder name in the path, and `url` to swagger-json in query of that URL). Than the frame loads swagger-content just fine. Minimal tweaks done to UI's (which was one of the goals, to have less-painful upgrades).

I guess, that iframe isn't technically necessary. I have it mostly to hide the URL out of the view (not as a secret, but to avoid creating confusion).

That's about it. Simple really :)

**Comment by MikeRalphson** [comment]
Added `try/catch` around the `screen.orientation.lock` call. Please chase if you seen any further issues with CORS.
